name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install gssapi extensions
        run: sudo apt-get install gcc python-dev libkrb5-dev
      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv -p python venv
          source venv/bin/activate
          pip install pilot-platform-common=="0.0.25"
          pip install -r requirements.txt -r tests/test_requirements.txt
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m pytest -c tests/pytest.ini
